### ISSUE TITLE
When sending array of event under default mapping String attributes are wrapped in additional quotes.

### ISSUE THREAD

**Issue by tishan89** [wso2-extensions/siddhi-map-json#2]
As an example if we send below

[Event{timestamp=-1, id=-1, data=["WSO2", 52.6, 100], isExpired=false}, 
Event{timestamp=-1, id=-1, data=["WSO2", 53.6, 99], isExpired=false}, 
Event{timestamp=-1, id=-1, data=["WSO2", 54.6, 80], isExpired=false}]

Output of symbol will be ""WSO2"". 
Applicable to this case because of use of Gson. 
Also please improve test-cases to validate all supported datatypes.

**Comment by minudika** [comment]
Fixed with PR #3.
