### ISSUE TITLE
Accept DOUBLE as Integer format

### ISSUE THREAD

**Issue by ricardojlrufino** [wso2-extensions/siddhi-map-json#37]
It would be interesting if integer values could be treated as double.
Ex: 120 or 120.0

Some libraries automatically remove the .0 at the time of converting to JSON

**Comment by mohanvive** [comment]
Use `convert` function for this purpose. Not planning to support this implicitly. 
https://siddhi.io/en/v5.1/docs/api/latest/#convert-function .
