### ISSUE TITLE
Plugin isn't building with Java 13 and Maven 3.6.3

### ISSUE THREAD

**Issue by vringar** [wso2-extensions/siddhi-map-json#88]
**Description:**
I just checked out the repository and ran `mvn clean package` to build the package for myself.
I got the following error message:
```
Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs (findbugs) on project siddhi-map-json-parent:
Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs for parameter pluginArtifacts:
Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList
```

**Suggested Labels:**
type/bug

**Affected Product Version:**
master @ 3d7ed8c926f328ff3197eaa632a70d0ad68a7232

**OS, DB, other environment details and versions:**    
Manjaro Linux with AdoptOpenJDK 13.0.1 and Maven 3.6.3
**Steps to reproduce:**
Checkout the repository and run `mvn clean package`

**Comment by vringar** [comment]
Issue persists with JDK 11, so I think Maven is to blame.
The [jenkins build](https://wso2.org/jenkins/job/siddhi/job/siddhi-map-json/lastBuild/io.siddhi.extension.map.json$siddhi-map-json-parent/) for this repo runs with Maven 3.0.5 and Java 8.
But the [official docs](https://siddhi.io/en/v5.1/development/build/) suggest a build should be possible with Java 11 and Maven 3.5.x.

**Comment by BuddhiWathsala** [comment]
@vringar, [the official docs](https://siddhi.io/en/v5.1/development/build/) suggested that you can only use Java 8 to build the projects. However, you can use Java 8 or Java 11 as the runtime after the build. There can be issues when you build using Java 11.

**Comment by vringar** [comment]
Ah okay, thanks for the clarification.
I understood the docs to mean that I should build with Java 8 if I want to run on a JRE 8, which I don't.
